#!/bin/bash
P="sudo -u postgres psql -p 5544 -d relbuild -tA"
echo "=== tables ==="
$P -c "SELECT relname, n_live_tup FROM pg_stat_user_tables ORDER BY n_live_tup DESC LIMIT 25"
echo "=== corpus_release ==="
$P -c "SELECT release_id, shard_key, state, (sealed_at IS NOT NULL) sealed, left(content_hash,12), snapshot_path FROM corpus_release ORDER BY release_id"
echo "=== active ==="
$P -c "SELECT * FROM corpus_release_active"
echo "=== mirror state ==="
$P -c "SELECT name, watermark, rows_done, detail FROM src_mirror_state"
echo "=== partitions ==="
$P -c "SELECT c.relname, pg_size_pretty(pg_total_relation_size(c.oid)) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname LIKE 'chunks_release%'"
echo "=== db sizes ==="
sudo -u postgres psql -p 5544 -tA -c "SELECT datname, pg_size_pretty(pg_database_size(datname)) FROM pg_database ORDER BY 1"
echo "=== extensions ==="
$P -c "SELECT extname, extversion FROM pg_extension ORDER BY 1"
echo "=== settings ==="
$P -c "SELECT name, setting, unit FROM pg_settings WHERE name IN ('shared_buffers','maintenance_work_mem','work_mem','max_parallel_maintenance_workers','listen_addresses','port','data_directory')"
echo "=== migration ledger? ==="
$P -c "SELECT to_regclass('schema_migrations')"
