"""The lexical channel and the backend seam behind it.

WHY A SEAM. Sparse retrieval here is PostgreSQL `to_tsvector('english', ...)` over the whole
corpus, ranked by raw match count. It is slow (a measured 20 s to 176 s for one pass) and, for the
39.9% of the corpus that is CJK, it is not degraded but dead: the `english` configuration has no
segmenter, so a Chinese or Japanese abstract produces lexemes nobody will ever query for.
Workstream C is replacing it with Tantivy. This module defines the contract both sides code
against; the Postgres implementation stays as the fallback and is what runs until Tantivy is live.

The interface is written down for workstream C in `docs/lexical_interface.md`. Change one and
change the other.
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field, replace
from datetime import date

from .base import FAMILY_OVERFETCH
from .legal import _date_clause

#  How many of the query's longest lexemes the general lexical channel ORs together.
#
#  MEASURED 2026-08-21 on the live corpus, one pass, same 1000-publication cap: 18 terms took
#  33.6 s and 8 took 8.5 s, both filling the cap. A deep run makes up to 39 passes and this channel
#  was 54% of each one, so the term count was worth about 22 minutes of a 112-minute search, more
#  than the entire vector side of retrieval, which is 0.01 s per ANN query.
#
#  The operator stays OR. Requiring all terms of a long query-by-example returns nothing: 18 AND
#  measured 0 publications, 4 AND measured 4. `channel_claim_bm25` can require AND because it is a
#  precision channel beside a broad one; this is the broad one.
BM25_TERMS = int(os.environ.get("BM25_TERMS", "8"))

#  The chunk kinds a lexical query may be pointed at. These are the values of `chunks.kind`, and
#  they are the "fields" of the interface: a Tantivy document is one chunk, and its field is its
#  kind.
FIELD_ABSTRACT = "abstract"
FIELD_CLAIM = "claim_own"
FIELD_CLAIM_RESOLVED = "claim_resolved"
FIELD_WHOLE = "whole"
FIELD_PARAGRAPH = "paragraph"
FIELD_TITLE = "title"
CLAIM_FIELDS = (FIELD_CLAIM, FIELD_CLAIM_RESOLVED)
#  The general lexical channel deliberately excludes description paragraphs: abstract, claims and
#  whole-document chunks carry the key terms, and including 14M paragraphs makes the match set and
#  the GROUP BY unbounded. Tantivy has no such problem and workstream C may widen this; the flag
#  is here so the change is a parameter and not an edit.
BROAD_FIELDS = (FIELD_ABSTRACT, FIELD_CLAIM, FIELD_CLAIM_RESOLVED, FIELD_WHOLE, FIELD_TITLE)


#  Every chunk kind this corpus holds. Field names are inlined into SQL rather than bound as
#  parameters (the queries are asserted on in the tests, and a bound parameter is invisible there),
#  so they are checked against this allowlist first: nothing outside it ever reaches a query string.
KNOWN_FIELDS = (FIELD_ABSTRACT, FIELD_CLAIM, FIELD_CLAIM_RESOLVED, FIELD_WHOLE, FIELD_PARAGRAPH,
                FIELD_TITLE, "figure_caption")


def _lit(kind):
    k = str(kind)
    if k not in KNOWN_FIELDS:
        raise ValueError(f"unknown lexical field {kind!r}; known: {KNOWN_FIELDS}")
    return "'" + k + "'"


def _kind_in(kinds):
    kinds = tuple(kinds or ())
    if not kinds:
        return ""
    return "c.kind IN (" + ",".join(_lit(k) for k in kinds) + ")"


@dataclass(frozen=True)
class LexicalHit:
    """One chunk that matched. THE result shape of the interface.

    `score` is the backend's own relevance and is NOT comparable across backends or across
    channels: fusion consumes the ORDER, never the number (see fusion.rrf).
    """
    publication_id: object          # bigint locally; a backend may carry its own id type
    chunk_id: object = None         # None when the backend cannot name the chunk
    score: float = 0.0
    field: str = ""                 # the chunk kind that matched
    snippet: str = ""               # matched text, for display and for evidence quotation


@dataclass(frozen=True)
class LexicalFilters:
    """What a lexical query is allowed to return.

    Two halves, on purpose:

      * STRUCTURAL, `kinds`, `exclude_kinds`, the date bounds and `exclude_family`. Every backend
        must honour these; they are expressible as a Tantivy filter or a Postgres WHERE alike.
      * `sql`, an escape hatch carrying the exact `(fragment, params)` the Postgres backend
        AND-s into its query. It exists because the citability window is generated by
        `search_modes.citable_where` and has jurisdiction-specific branches; reproducing it as
        structural fields would be a second implementation of the legal rules, which is precisely
        the bug this codebase must not have twice. A non-Postgres backend IGNORES `sql` and must
        implement the structural fields, which `from_subject_mode` fills in from the same subject.
    """
    kinds: tuple = ()                       # include only these chunk kinds; () = all
    exclude_kinds: tuple = ()               # never these
    published_before: date = None           # publication_date < this
    published_after: date = None            # publication_date > this
    effective_filing_before: date = None    # COALESCE(earliest_priority, filing) < this
    exclude_family_of: str = None           # publication_number whose simple family is excluded
    mode: str = None                        # 'novelty' | 'inventive_step'; how the dates combine
    sql: tuple = ("", ())                   # Postgres-only: (fragment, params), alias `p`

    @classmethod
    def from_subject_mode(cls, subject, mode, **kw):
        """Build the filter set for a (subject, mode) pair. () / None when there is no subject."""
        frag, params = _date_clause(subject, mode)
        efd = getattr(subject, "efd", None) if subject is not None else None
        m = getattr(mode, "value", mode)
        return cls(
            sql=(frag, tuple(params)),
            mode=m,
            #  Both modes bar anything published on or after the subject's effective filing date
            #  from being PUBLIC prior art. Novelty additionally reaches earlier-filed,
            #  later-published art; that second window is the `effective_filing_before` term, and
            #  a backend that cannot express the disjunction must fall back to the safe half.
            published_before=efd if m == "inventive_step" else None,
            effective_filing_before=efd if m == "novelty" else None,
            exclude_family_of=getattr(subject, "number", None) if subject is not None else None,
            **kw)

    def with_fields(self, fields):
        return replace(self, kinds=tuple(fields or ()))


class LexicalBackend:
    """A lexical index this engine can query. Implement all three methods.

    `available()` decides whether the orchestrator uses this backend at all; a backend that is
    still building must say False rather than return an empty result set, because an empty result
    is indistinguishable from a genuine miss and would be scored as one.
    """

    name = "abstract"

    def available(self) -> bool:
        raise NotImplementedError

    def search(self, query, *, fields=(), filters=None, limit=1000, operator="or",
               max_terms=None, rank="density") -> list:
        """-> [LexicalHit] best-first. `operator` is "or" or "and"; `max_terms` truncates the
        query to its N most specific terms; `rank` is a hint, "density" or "match_count"."""
        raise NotImplementedError

    def publications(self, query, *, fields=(), filters=None, limit=1000, operator="or",
                     max_terms=None, rank="density") -> list:
        """-> [(publication_id, score)] best-first, one row per publication.

        Default implementation folds `search`; a backend that can aggregate in its own engine
        should override, because pulling every matching chunk back to fold in Python is the
        expensive shape.
        """
        best = {}
        for h in self.search(query, fields=fields, filters=filters, limit=limit,
                             operator=operator, max_terms=max_terms, rank=rank):
            if h.publication_id not in best:
                best[h.publication_id] = h.score
        return list(best.items())


class PostgresLexicalBackend(LexicalBackend):
    """`to_tsvector('english', ...)` + GIN, the implementation that is live today.

    It is bound to a Retriever because it reuses that retriever's connection, its funnel widths
    and its family-collapse aggregation; the queries below are the ones the channels have always
    run and are kept byte-for-byte so the fallback is the known-good path.
    """

    name = "postgres_tsvector"

    def __init__(self, retriever):
        self.r = retriever

    def available(self) -> bool:
        return True

    # -- the deadline --------------------------------------------------------------------------
    def _deadline_ms(self):
        try:
            import search_settings as _ss
            return max(0, int(_ss.get("lexical_timeout_ms")))
        except Exception:
            return 0

    def _bounded(self, run):
        """One lexical query under a deadline, so a slow channel cannot own the pass.

        THE MEASUREMENT. This channel is Postgres `to_tsvector('english')` over every chunk in the
        corpus. It was measured at 20 s to 176 s for ONE pass when the corpus held 1.4M chunks; it
        now holds 11.2M. On a deep run making up to 39 passes it was 54% of every one of them,
        worth about 22 minutes of a 112-minute search, which is more than the entire vector side of
        retrieval costs.

        It is also the lowest-weighted channel in the fusion, on purpose: it ranks by raw lexeme
        count, and for CJK text the `english` configuration has no segmenter, so there it is not
        degraded but dead.

        A pass that hits the deadline returns nothing FROM THIS CHANNEL and records that it did,
        through `failclosed`. "The keyword channel timed out" and "the keyword channel found
        nothing" are different statements, and letting the second stand for the first is exactly
        the class of bug `failclosed` was written for.
        """
        ms = self._deadline_ms()
        if ms <= 0:
            return run()
        conn = self.r.conn
        try:
            with conn.cursor() as c:
                c.execute("SET statement_timeout = %d" % ms)
        except Exception:
            return run()                      # cannot arm it: run unbounded rather than not at all
        try:
            return run()
        except Exception as e:
            import psycopg
            cancelled = isinstance(e, getattr(psycopg.errors, "QueryCanceled", ())) or (
                "statement timeout" in str(e).lower())
            if not cancelled:
                raise
            import failclosed
            return failclosed.fallback(
                "retrieval.lexical",
                "keyword channel exceeded its %d ms deadline" % ms, [],
                kind="lexical_timeout")
        finally:
            #  Always disarm: this connection is per-thread and lives for the life of the process,
            #  so a timeout left set here would silently apply to the dense channel next.
            try:
                with conn.cursor() as c:
                    c.execute("SET statement_timeout = 0")
            except Exception:
                pass

    # -- the two production queries ----------------------------------------------------------
    def publications(self, query, *, fields=(), filters=None, limit=1000, operator="or",
                     max_terms=None, rank="density"):
        if not query or not query.strip():
            return []
        filters = filters or LexicalFilters()
        dc, dp = filters.sql
        dp = list(dp)
        terms = int(max_terms or BM25_TERMS)
        op = " & " if str(operator).lower() == "and" else " | "
        kinds = tuple(fields or filters.kinds or ())
        if rank == "match_count":
            # Rank publications by the COUNT of matching chunks (how many of the doc's
            # claims/abstract hit the query lexemes) instead of ts_rank_cd over every match,
            # count(*) is far cheaper than density ranking, and RRF fuses by rank anyway.
            kind_clause = _kind_in(kinds) or "c.kind <> 'paragraph'"
            sql = (f"WITH tq AS (SELECT to_tsquery('english', NULLIF(array_to_string(ARRAY("
                   f"  SELECT w FROM unnest(tsvector_to_array(to_tsvector('english', %s))) w "
                   f"  ORDER BY length(w) DESC LIMIT {terms}), '{op}'), '')) q) "
                   f"SELECT c.publication_id, count(*) AS score "
                   f"FROM chunks c JOIN publications p ON p.id=c.publication_id, tq "
                   f"WHERE tq.q IS NOT NULL AND {kind_clause} AND c.tsv @@ tq.q {dc} "
                   f"GROUP BY c.publication_id ORDER BY score DESC LIMIT %s")
            return self._bounded(lambda: self.r._families_from_chunks(
                sql, [query, *dp, limit * FAMILY_OVERFETCH], limit))
        kc = _kind_in(kinds)
        kind_clause = (kc + " AND ") if kc else ""
        sql = (f"WITH tq AS (SELECT to_tsquery('english', NULLIF(array_to_string(ARRAY("
               f"  SELECT w FROM unnest(tsvector_to_array(to_tsvector('english', %s))) w "
               f"  ORDER BY length(w) DESC LIMIT {terms}), '{op}'), '')) q) "
               f"SELECT c.publication_id, max(ts_rank_cd(c.tsv, tq.q)) AS score "
               f"FROM chunks c JOIN publications p ON p.id=c.publication_id, tq "
               f"WHERE tq.q IS NOT NULL AND {kind_clause}"
               f"c.tsv @@ tq.q {dc} GROUP BY c.publication_id ORDER BY score DESC LIMIT %s")
        return self._bounded(lambda: self.r._families_from_chunks(
            sql, [query, *dp, limit * FAMILY_OVERFETCH], limit))

    def search(self, query, *, fields=(), filters=None, limit=1000, operator="or",
               max_terms=None, rank="density"):
        """Chunk-level hits, the shape workstream C's index returns natively.

        Nothing in the production path calls this yet, the channels want publications, but it is
        implemented rather than stubbed so the contract is executable on both sides and the
        interface document is testable.
        """
        if not query or not query.strip():
            return []
        filters = filters or LexicalFilters()
        dc, dp = filters.sql
        terms = int(max_terms or BM25_TERMS)
        op = " & " if str(operator).lower() == "and" else " | "
        kinds = tuple(fields or filters.kinds or ())
        kc = _kind_in(kinds)
        if not kc and filters.exclude_kinds:
            kc = "c.kind NOT IN (" + ",".join(_lit(k) for k in filters.exclude_kinds) + ")"
        kind_clause = (kc + " AND ") if kc else ""
        sql = (f"WITH tq AS (SELECT to_tsquery('english', NULLIF(array_to_string(ARRAY("
               f"  SELECT w FROM unnest(tsvector_to_array(to_tsvector('english', %s))) w "
               f"  ORDER BY length(w) DESC LIMIT {terms}), '{op}'), '')) q) "
               f"SELECT c.id AS chunk_id, c.publication_id, c.kind, "
               f"       ts_rank_cd(c.tsv, tq.q) AS score, left(c.text, 400) AS snippet "
               f"FROM chunks c JOIN publications p ON p.id=c.publication_id, tq "
               f"WHERE tq.q IS NOT NULL AND {kind_clause}c.tsv @@ tq.q {dc} "
               f"ORDER BY score DESC LIMIT %s")
        with self.r.conn.cursor() as c:
            c.execute(sql, [query, *dp, limit])
            return [LexicalHit(publication_id=r["publication_id"], chunk_id=r["chunk_id"],
                               score=float(r["score"]), field=r["kind"],
                               snippet=r["snippet"] or "")
                    for r in c.fetchall()]


#  Workstream C registers its backend here. Until it does, `backend()` returns the Postgres one.
_BACKEND_FACTORY = None


def register_backend(factory):
    """factory(retriever) -> LexicalBackend. Called once at startup by whoever owns the index."""
    global _BACKEND_FACTORY
    _BACKEND_FACTORY = factory


def backend(retriever):
    """The lexical backend this retriever should use: the registered one if it is available,
    the Postgres fallback otherwise. Never returns None, never raises."""
    if _BACKEND_FACTORY is not None:
        try:
            b = _BACKEND_FACTORY(retriever)
            if b is not None and b.available():
                return b
        except Exception:
            pass
    return PostgresLexicalBackend(retriever)


class LexicalMixin:
    """The two lexical channels plus the bibliographic prior, which is the same kind of query."""

    def lexical(self):
        """This retriever's lexical backend, resolved once per retriever."""
        b = self.__dict__.get("_lexical")
        if b is None:
            b = self.__dict__["_lexical"] = backend(self)
        return b

    def channel_bm25(self, q, subject=None, mode=None):
        # OR the query's lexemes (websearch/plainto AND every term -> a long query-by-example
        # text would match nothing). ts_rank_cd still ranks by term density. GIN-indexed, capped
        # to BM25_TERMS of the most specific (longest) terms, and restricted to non-paragraph
        # chunks (abstract/claims/whole carry the key terms; excluding descriptions keeps the
        # match set and the GROUP BY bounded -> fast).
        if not q or not q.strip():
            return []
        return self.lexical().publications(
            q, filters=LexicalFilters.from_subject_mode(subject, mode),
            limit=self._cap(), operator="or", max_terms=BM25_TERMS, rank="match_count")

    def channel_claim_bm25(self, q, subject=None, mode=None):
        """Precise lexical search restricted to claims, fused with claim_dense by weighted RRF.

        Claim mode used to OR as many as 18 terms and then group every matching claim chunk.  On
        the 25M-chunk corpus, a short element such as ``base plate controller`` matched millions of
        rows and one pass took more than five minutes in production.  Claim-dense already supplies
        the broad-recall channel, so this complementary lexical channel deliberately requires the
        four most specific (longest) stemmed terms.  The GIN index can intersect those postings
        directly, keeping the pass bounded while still surfacing literal claim-language matches.
        """
        if not q or not q.strip():
            return []
        return self.lexical().publications(
            q, fields=CLAIM_FIELDS, filters=LexicalFilters.from_subject_mode(subject, mode),
            limit=self._cap(), operator="and", max_terms=4, rank="density")

    def channel_biblio(self, assignee_hints, subject=None, mode=None):
        """Assignee / inventor prior.

        MEASURED: `parties` holds 7,047,028 inventor rows and ZERO applicant rows, so an assignee
        hint matches nothing and this channel cannot fire on the signal it was built for. It is
        kept wired because the column is populated by ingest, not by retrieval, and the day the
        applicant rows land the channel starts working with no code change.
        """
        if not assignee_hints:
            return []
        dc, dp = _date_clause(subject, mode)
        like = " OR ".join(["pa.normalized_name LIKE %s"] * len(assignee_hints))
        params = [f"%{a.upper()}%" for a in assignee_hints] + list(dp)
        sql = (f"SELECT p.id AS publication_id, count(*) AS score FROM parties pa "
               f"JOIN publications p ON p.id=pa.publication_id WHERE ({like}) {dc} "
               f"GROUP BY p.id ORDER BY score DESC LIMIT %s")
        with self.conn.cursor() as c:
            c.execute(sql, params + [self._cap() * FAMILY_OVERFETCH])
            rows = [(r["publication_id"], r["score"]) for r in c.fetchall()]
        return self.collapse_pairs(rows, self._cap())
