"""Reading and writing the release tables, and the one transaction that switches a shard over.

ACTIVATION IS THE ONLY MOMENT THIS SYSTEM CHANGES WHAT IT SEARCHES. Everything else here is
bookkeeping. So the rules are narrow and they are enforced, not documented:

    * a release must be SEALED before it can be activated. A sealed release is immutable in the
      database (sql/010 trigger), so what gets activated cannot be edited afterwards;
    * activation is ONE transaction covering every shard key it touches, so a reader either sees
      the whole new generation or the whole old one. A query cannot fan out across two
      generations, because there is no instant at which two generations are both visible;
    * activation is gated on the release's completeness statistics against the release it
      replaces. A release that is worse than its predecessor is refused before it serves, not
      discovered afterwards;
    * rollback SWAPS the pair. Rolling back sets active to the previous release and previous to
      the one you left, so rolling back a rollback returns to where you were, and the switch is
      reversible in both directions rather than one.
"""
from __future__ import annotations

import json
import os

import psycopg
from psycopg.rows import dict_row

#  The builder never connects to production by default. `config.PG_DSN` is the live corpus; a
#  release database is a separate DSN that has to be named on purpose.
RELEASE_DSN_ENV = "CORPUS_RELEASE_DSN"

SEALABLE_STATES = ("building", "built")
ACTIVATABLE_STATES = ("built", "verified", "superseded")


class ReleaseError(RuntimeError):
    pass


class NotSealed(ReleaseError):
    pass


class StatsRegression(ReleaseError):
    """Raised instead of activating a release whose completeness went backwards."""

    def __init__(self, message, regressions):
        super().__init__(message)
        self.regressions = list(regressions or [])


def dsn(explicit=None):
    d = explicit or os.environ.get(RELEASE_DSN_ENV) or ""
    if not d:
        raise ReleaseError(
            f"no release DSN: set {RELEASE_DSN_ENV}. There is deliberately no default, because a "
            f"default that happens to be the production corpus is how an offline builder builds "
            f"an HNSW index on the live database.")
    return d


def connect(explicit=None, autocommit=False):
    return psycopg.connect(dsn(explicit), row_factory=dict_row, autocommit=autocommit)


def _j(v):
    return json.dumps(v or {}, default=str)


# ---------------------------------------------------------------------------------------------
# creating and sealing
# ---------------------------------------------------------------------------------------------
def next_version(conn, shard_key):
    with conn.cursor() as cur:
        cur.execute("SELECT COALESCE(max(version), 0) + 1 v FROM corpus_release WHERE shard_key=%s",
                    (shard_key,))
        return int(cur.fetchone()["v"])


def release_id_for(shard_key, version):
    return f"{shard_key}_v{int(version)}"


def create(conn, *, shard_key, version=None, kind="domain", builder="", note=""):
    """Open a new release for building. State `building`, not sealed, no content hash yet."""
    version = int(version or next_version(conn, shard_key))
    rid = release_id_for(shard_key, version)
    with conn.cursor() as cur:
        cur.execute("""INSERT INTO corpus_release (release_id, shard_key, version, kind, state,
                                                   builder, note)
                       VALUES (%s,%s,%s,%s,'building',%s,%s) RETURNING *""",
                    (rid, shard_key, version, kind, builder, note))
        return cur.fetchone()


def ensure_partition(conn, release_id):
    """One partition per release. This is what makes immutability physical: a release is built
    into its own heap, indexed once, and retired by DETACH rather than by a DELETE that would
    rewrite the HNSW graph of every other release sharing the table."""
    name = partition_name(release_id)
    with conn.cursor() as cur:
        cur.execute("SELECT to_regclass(%s) t", (name,))
        if cur.fetchone()["t"] is not None:
            return name
        #  release_id is generated by `release_id_for` from a shard key this module owns; it is
        #  still validated here, because an identifier reaching DDL by string interpolation is
        #  worth one explicit check rather than an assumption about every caller.
        if not _safe_ident(release_id):
            raise ReleaseError(f"unsafe release_id for a partition name: {release_id!r}")
        #  `FOR VALUES IN` takes a literal, not a parameter: Postgres cannot infer the type of a
        #  bind parameter in partition bound DDL. `_safe_ident` above is what makes the literal
        #  safe, which is why it is checked rather than assumed.
        cur.execute(f'CREATE TABLE "{name}" PARTITION OF chunks_release '
                    f"FOR VALUES IN ('{release_id}')")
    return name


def partition_name(release_id):
    return f"chunks_release_{release_id}"


def _safe_ident(s):
    s = str(s or "")
    return bool(s) and len(s) <= 48 and all(c.isalnum() or c == "_" for c in s) and not s[0].isdigit()


def build_indexes(conn, release_id, *, m=16, ef_construction=64, halfvec=False,
                  maintenance_work_mem=None, parallel_workers=None):
    """The dense index, built on the release's own partition, offline.

    NEVER run this against a serving database. pgvector holds the whole graph in
    `maintenance_work_mem` and falls back to a much slower two-phase on-disk build when it does
    not fit, so the builder box has to be at least as large as the shard it is building for. See
    `corpus.sizing.build_ram_required_gib`.
    """
    part = partition_name(release_id)
    if not _safe_ident(release_id):
        raise ReleaseError(f"unsafe release_id: {release_id!r}")
    col = "embedding::halfvec(768)" if halfvec else "embedding"
    opclass = "halfvec_cosine_ops" if halfvec else "vector_cosine_ops"
    params = {"type": "hnsw", "opclass": opclass, "m": int(m),
              "ef_construction": int(ef_construction), "dim": 768,
              "halfvec": bool(halfvec)}
    with conn.cursor() as cur:
        if maintenance_work_mem:
            cur.execute(f"SET maintenance_work_mem = '{maintenance_work_mem}'")
        if parallel_workers is not None:
            cur.execute(f"SET max_parallel_maintenance_workers = {int(parallel_workers)}")
        cur.execute(f'CREATE INDEX IF NOT EXISTS "ix_{part}_hnsw" ON "{part}" '
                    f'USING hnsw (({col}) {opclass}) '
                    f'WITH (m = {int(m)}, ef_construction = {int(ef_construction)})')
        cur.execute(f'CREATE INDEX IF NOT EXISTS "ix_{part}_family" ON "{part}" (family_key)')
        cur.execute(f'CREATE INDEX IF NOT EXISTS "ix_{part}_pub" ON "{part}" (publication_id)')
        cur.execute(f'CREATE INDEX IF NOT EXISTS "ix_{part}_kind" ON "{part}" (kind)')
        cur.execute(f'ANALYZE "{part}"')
    return params


def observed_index_params(conn, release_id):
    """What the database actually reports for this release's dense index, for `manifest.verify`."""
    part = partition_name(release_id)
    with conn.cursor() as cur:
        cur.execute("SELECT indexdef FROM pg_indexes WHERE indexname = %s", (f"ix_{part}_hnsw",))
        row = cur.fetchone()
    if not row:
        return {}
    d = row["indexdef"]
    out = {"type": "hnsw", "dim": 768,
           "opclass": "halfvec_cosine_ops" if "halfvec_cosine_ops" in d else "vector_cosine_ops",
           "halfvec": "halfvec" in d}
    for key in ("m", "ef_construction"):
        marker = f"{key}='"
        if marker in d:
            out[key] = int(d.split(marker, 1)[1].split("'", 1)[0])
    return out


def index_bytes(conn, release_id):
    part = partition_name(release_id)
    with conn.cursor() as cur:
        cur.execute("SELECT COALESCE(pg_indexes_size(to_regclass(%s)), 0) idx, "
                    "COALESCE(pg_total_relation_size(to_regclass(%s)), 0) total", (part, part))
        r = cur.fetchone()
    return {"index_bytes": int(r["idx"]), "total_bytes": int(r["total"])}


def add_members(conn, release_id, rows):
    """rows: dicts with family_key, home_domain, secondary_domains, n_publications, n_chunks."""
    if not rows:
        return 0
    with conn.cursor() as cur:
        with cur.copy("COPY corpus_release_member (release_id, family_key, home_domain, "
                      "secondary_domains, n_publications, n_chunks, source) FROM STDIN") as cp:
            for r in rows:
                cp.write_row((release_id, r["family_key"], r["home_domain"],
                              list(r.get("secondary_domains") or []),
                              int(r.get("n_publications") or 0), int(r.get("n_chunks") or 0),
                              r.get("source") or "corpus"))
    return len(rows)


def set_shard_rows(conn, release_id, rows):
    if not rows:
        return 0
    with conn.cursor() as cur:
        for r in rows:
            cur.execute("""INSERT INTO corpus_release_shard (release_id, domain, n_families,
                               n_publications, n_chunks, index_bytes, disk_bytes)
                           VALUES (%s,%s,%s,%s,%s,%s,%s)
                           ON CONFLICT (release_id, domain) DO UPDATE SET
                               n_families=EXCLUDED.n_families,
                               n_publications=EXCLUDED.n_publications,
                               n_chunks=EXCLUDED.n_chunks,
                               index_bytes=EXCLUDED.index_bytes,
                               disk_bytes=EXCLUDED.disk_bytes""",
                        (release_id, r["domain"], int(r.get("n_families") or 0),
                         int(r.get("n_publications") or 0), int(r.get("n_chunks") or 0),
                         int(r.get("index_bytes") or 0), int(r.get("disk_bytes") or 0)))
    return len(rows)


def seal(conn, release_id, manifest, *, snapshot_path="", snapshot_sha256="", snapshot_bytes=0,
         state="built"):
    """Stamp the manifest and close the release for editing.

    After this the sql/010 trigger refuses every column but `state`, so the counts, the checksums
    and the index parameters a shard verifies against cannot drift from what was built.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT state, sealed_at FROM corpus_release WHERE release_id=%s FOR UPDATE",
                    (release_id,))
        row = cur.fetchone()
        if not row:
            raise ReleaseError(f"no such release: {release_id}")
        if row["sealed_at"] is not None:
            raise ReleaseError(f"release {release_id} is already sealed")
        if row["state"] not in SEALABLE_STATES:
            raise ReleaseError(f"release {release_id} is {row['state']}, not sealable")
        cur.execute("""UPDATE corpus_release SET state=%s, content_hash=%s, manifest=%s,
                           built_from=%s, counts=%s, index_params=%s, stats=%s,
                           snapshot_path=%s, snapshot_sha256=%s, snapshot_bytes=%s,
                           built_at=COALESCE(built_at, now()), sealed_at=now()
                       WHERE release_id=%s RETURNING *""",
                    (state, manifest.get("content_hash", ""), _j(manifest),
                     _j(manifest.get("built_from")), _j(manifest.get("counts")),
                     _j(manifest.get("index_params")), _j(manifest.get("stats")),
                     snapshot_path, snapshot_sha256, int(snapshot_bytes), release_id))
        return cur.fetchone()


def get(conn, release_id):
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM corpus_release WHERE release_id=%s", (release_id,))
        return cur.fetchone()


def members(conn, release_id, limit=None):
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM corpus_release_member WHERE release_id=%s ORDER BY family_key"
                    + (" LIMIT %s" if limit else ""),
                    (release_id, limit) if limit else (release_id,))
        return cur.fetchall()


def shard_domains(conn, release_id):
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM corpus_release_shard WHERE release_id=%s ORDER BY domain",
                    (release_id,))
        return cur.fetchall()


def releases_for_domain(conn, domain):
    """Which releases hold this domain. The domain -> shard lookup `shard_router.route()` feeds."""
    with conn.cursor() as cur:
        cur.execute("""SELECT s.release_id, r.shard_key, a.shard_key IS NOT NULL AS is_active
                       FROM corpus_release_shard s
                       JOIN corpus_release r ON r.release_id = s.release_id
                       LEFT JOIN corpus_release_active a ON a.release_id = s.release_id
                       WHERE s.domain = %s ORDER BY is_active DESC, r.shard_key""", (domain,))
        return cur.fetchall()


# ---------------------------------------------------------------------------------------------
# the switch
# ---------------------------------------------------------------------------------------------
def active(conn, shard_key):
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM corpus_release_active WHERE shard_key=%s", (shard_key,))
        return cur.fetchone()


def active_set(conn):
    """The whole fleet's active releases, read in ONE statement.

    One statement is one MVCC snapshot. Because activation is one transaction, a reader here can
    never see half of a switch, which is the property that keeps a query inside one generation.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT shard_key, release_id, previous_release_id, generation, activated_at "
                    "FROM corpus_release_active ORDER BY shard_key")
        return {r["shard_key"]: r for r in cur.fetchall()}


def _gate(conn, new_row, prev_release_id, force):
    """Refuse a release whose completeness went backwards. `force` records the override rather
    than hiding it."""
    from corpus import stats as stats_mod          # local: stats imports nothing from here
    if force or not prev_release_id:
        return []
    prev = get(conn, prev_release_id)
    cmp = stats_mod.compare(dict((prev or {}).get("stats") or {}),
                            dict(new_row.get("stats") or {}))
    if cmp["regressions"]:
        raise StatsRegression(
            f"{new_row['release_id']} is worse than {prev_release_id}: "
            + "; ".join(c["detail"] for c in cmp["regressions"]), cmp["regressions"])
    return cmp["regressions"]


def activate(conn, release_id, *, actor="", reason="", force=False, commit=True):
    """Switch one shard key over. One transaction, gated, reversible."""
    return activate_many(conn, [release_id], actor=actor, reason=reason, force=force,
                         commit=commit)


def activate_many(conn, release_ids, *, actor="", reason="", force=False, commit=True):
    """Switch several shard keys over in ONE transaction.

    This is the multi-shard case the fan-out cares about: a search asks the hot shard and two
    domain shards, and if those three switched in three transactions there is a window in which
    the answer is assembled from two generations of the corpus. There is no such window here.

    `commit=False` leaves the transaction open, which is how the test proves that a concurrent
    reader sees none of it until the commit.
    """
    if conn.autocommit:
        raise ReleaseError("activation needs a transactional connection; autocommit is on")
    done = []
    with conn.cursor() as cur:
        cur.execute("SELECT nextval('corpus_release_generation_seq') g")
        generation = int(cur.fetchone()["g"])
        for release_id in release_ids:
            cur.execute("SELECT * FROM corpus_release WHERE release_id=%s FOR UPDATE",
                        (release_id,))
            rel = cur.fetchone()
            if not rel:
                raise ReleaseError(f"no such release: {release_id}")
            if rel["sealed_at"] is None:
                raise NotSealed(f"release {release_id} is not sealed and cannot be activated")
            if rel["state"] not in ACTIVATABLE_STATES and rel["state"] != "active":
                raise ReleaseError(f"release {release_id} is {rel['state']}, not activatable")

            cur.execute("SELECT * FROM corpus_release_active WHERE shard_key=%s FOR UPDATE",
                        (rel["shard_key"],))
            cur_active = cur.fetchone()
            prev_id = cur_active["release_id"] if cur_active else None
            if prev_id == release_id:
                done.append({"shard_key": rel["shard_key"], "release_id": release_id,
                             "generation": cur_active["generation"], "unchanged": True})
                continue
            _gate(conn, rel, prev_id, force)

            cur.execute("""INSERT INTO corpus_release_active (shard_key, release_id,
                               previous_release_id, generation, activated_at, activated_by, reason)
                           VALUES (%s,%s,%s,%s, now(), %s, %s)
                           ON CONFLICT (shard_key) DO UPDATE SET
                               release_id = EXCLUDED.release_id,
                               previous_release_id = EXCLUDED.previous_release_id,
                               generation = EXCLUDED.generation,
                               activated_at = EXCLUDED.activated_at,
                               activated_by = EXCLUDED.activated_by,
                               reason = EXCLUDED.reason
                           RETURNING *""",
                        (rel["shard_key"], release_id, prev_id, generation, actor,
                         reason + (" [forced]" if force else "")))
            row = cur.fetchone()
            cur.execute("UPDATE corpus_release SET state='active' WHERE release_id=%s",
                        (release_id,))
            if prev_id:
                cur.execute("UPDATE corpus_release SET state='superseded' WHERE release_id=%s",
                            (prev_id,))
            done.append({"shard_key": row["shard_key"], "release_id": row["release_id"],
                         "previous_release_id": row["previous_release_id"],
                         "generation": row["generation"], "unchanged": False})
    if commit:
        conn.commit()
    return {"generation": generation, "activated": done}


def rollback(conn, shard_key, *, actor="", reason="", commit=True):
    """Return a shard key to the release it was serving before, in one transaction.

    The pair is SWAPPED, not popped: `previous_release_id` becomes the release being rolled back
    from. So a rollback is itself reversible, and an operator who rolls back the wrong shard can
    undo it with the same call rather than needing a build.
    """
    if conn.autocommit:
        raise ReleaseError("rollback needs a transactional connection; autocommit is on")
    with conn.cursor() as cur:
        cur.execute("SELECT * FROM corpus_release_active WHERE shard_key=%s FOR UPDATE",
                    (shard_key,))
        row = cur.fetchone()
        if not row:
            raise ReleaseError(f"{shard_key} has no active release")
        if not row["previous_release_id"]:
            raise ReleaseError(f"{shard_key} has no previous release to roll back to")
        cur.execute("SELECT nextval('corpus_release_generation_seq') g")
        generation = int(cur.fetchone()["g"])
        from_id, to_id = row["release_id"], row["previous_release_id"]
        cur.execute("""UPDATE corpus_release_active SET release_id=%s, previous_release_id=%s,
                           generation=%s, activated_at=now(), activated_by=%s, reason=%s
                       WHERE shard_key=%s RETURNING *""",
                    (to_id, from_id, generation, actor,
                     reason or f"rollback from {from_id}", shard_key))
        out = cur.fetchone()
        cur.execute("UPDATE corpus_release SET state='active' WHERE release_id=%s", (to_id,))
        cur.execute("UPDATE corpus_release SET state='superseded' WHERE release_id=%s", (from_id,))
    if commit:
        conn.commit()
    return {"shard_key": shard_key, "release_id": to_id, "previous_release_id": from_id,
            "generation": out["generation"], "rolled_back_from": from_id}


# ---------------------------------------------------------------------------------------------
# the shard's own check
# ---------------------------------------------------------------------------------------------
def observed_counts(conn, release_id):
    with conn.cursor() as cur:
        cur.execute('SELECT count(*) n FROM chunks_release WHERE release_id=%s', (release_id,))
        chunks = int(cur.fetchone()["n"])
        cur.execute("SELECT count(*) n FROM corpus_release_member WHERE release_id=%s",
                    (release_id,))
        fams = int(cur.fetchone()["n"])
        cur.execute("SELECT count(DISTINCT publication_id) n FROM chunks_release WHERE release_id=%s",
                    (release_id,))
        pubs = int(cur.fetchone()["n"])
    return {"chunks": chunks, "families": fams, "publications": pubs}


def verify_serving(conn, release_id, *, artifact_root=None):
    """"Am I serving the release I think I am?"

    Recomputes the manifest hash, rechecks every artifact on disk, recounts the rows and rereads
    the index definition. A shard that cannot answer yes must not join the fan-out: a stale shard
    does not fail a search, it silently answers from an older corpus, which is the failure mode
    nobody notices.
    """
    from corpus import manifest as manifest_mod
    rel = get(conn, release_id)
    if not rel:
        v = manifest_mod.Verification()
        return v.add("release_present", False, f"no row for {release_id}")
    m = rel["manifest"] or {}
    v = manifest_mod.verify(m, artifact_root=artifact_root,
                            observed_counts=observed_counts(conn, release_id),
                            observed_index_params=observed_index_params(conn, release_id))
    v.add("sealed", rel["sealed_at"] is not None, f"state={rel['state']}")
    v.add("content_hash_recorded", bool(rel["content_hash"])
          and rel["content_hash"] == m.get("content_hash"),
          f"row {rel['content_hash']} != manifest {m.get('content_hash')}")
    return v
